# Generated by Django 5.1 on 2024-08-31 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "slug",
                    models.CharField(default="#", max_length=200, verbose_name="Слаг"),
                ),
                ("body", models.TextField(verbose_name="Содержание")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/preview",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата создания"
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="Статус публикации")),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Счетчик просмотров"),
                ),
            ],
        ),
    ]
