# Generated by Django 5.1 on 2024-08-31 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="is_active",
            new_name="is_published",
        ),
    ]
