# Generated by Django 5.1 on 2024-09-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_blog", "0002_rename_is_active_blog_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Блог", "verbose_name_plural": "Блоги"},
        ),
    ]
