# Generated by Django 5.1 on 2024-08-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product_catalog/photo",
                verbose_name="картинка",
            ),
        ),
    ]
