# Generated by Django 5.1 on 2024-09-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("id",),
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
