# Generated by Django 5.1 on 2024-09-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0005_productcharacteristics"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductCharacteristics",
        ),
    ]
