# Generated by Django 5.1 on 2024-09-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0008_alter_product_standard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="standard",
        ),
    ]
