# Generated by Django 5.1 on 2024-09-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0010_remove_product_is_active_version"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="version",
            constraint=models.UniqueConstraint(
                fields=("product", "number"), name="unique_versions"
            ),
        ),
    ]
