# Generated by Django 5.1 on 2024-09-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0011_version_unique_versions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="version",
            name="unique_versions",
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.UniqueConstraint(
                fields=("product", "number"),
                name="unique_versions",
                violation_error_message="Номер версии должен быть уникальным",
            ),
        ),
    ]
