# Generated by Django 4.2 on 2024-09-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0013_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
