# Generated by Django 4.2 on 2024-09-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0014_product_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("id",),
                "permissions": [("set_published", "Can publish products")],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="is_active",
            new_name="is_published",
        ),
    ]
