# Generated by Django 4.2 on 2024-09-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0015_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("id",),
                "permissions": [
                    ("set_published", "Can publish products"),
                    ("change_description", "Can change description"),
                    ("change_category", "Can change category"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
